//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mambo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMMENT_ARTICLE
    {
        public int id { get; set; }
        public int userID { get; set; }
        public int articleID { get; set; }
        public System.DateTime creationDate { get; set; }
        public string commentContent { get; set; }
    
        public virtual T_ARTICLE T_ARTICLE { get; set; }
        public virtual T_USER T_USER { get; set; }
    }
}
