//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mambo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RESOURCES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_RESOURCES()
        {
            this.T_ARTICLE = new HashSet<T_ARTICLE>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string path { get; set; }
        public int languageID { get; set; }
    
        public virtual T_LANGUAGE T_LANGUAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ARTICLE> T_ARTICLE { get; set; }
    }
}
