//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mambo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TRANSLATION
    {
        public int id { get; set; }
        public int articleID { get; set; }
        public int translatorID { get; set; }
        public int language { get; set; }
        public string translationArticleContent { get; set; }
        public string translationArticleTitle { get; set; }
    
        public virtual T_ARTICLE T_ARTICLE { get; set; }
        public virtual T_LANGUAGE T_LANGUAGE { get; set; }
        public virtual T_USER T_USER { get; set; }
    }
}
